newCoding/ui/projects/uicloud/polls/urls.py
from django.conf.urls import url

from . import views

#add an app_name to set the application namespace
app_name = 'polls'
'''
urlpatterns = [
    # ex: /polls/
    url(r'^$',views.index, name='index'),
    # ex: /polls/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]
'''

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^dbtest/$', views.DbView.as_view(), name='dbview'),
]

newCoding/ui/projects/uicloud/uicloud/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth import views as auth_views

from polls import views as polls_views
from . import views

urlpatterns = [
    url(r'^$', polls_views.IndexView.as_view(), name='index'),
    url(r'^uiaccounts/', include('uiaccounts.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    url(r"^dataCollection/",include("dataCollection.urls")),
    url(r"^pallasdata$",views.IndexView.as_view()),
    url(r"^dashboard/", include("dashboard.urls")),
    url(r"^filterConditionAdd$",views.filterConditionAdd),
    url(
        r'^api-auth/',
        include('rest_framework.urls', namespace='rest_framework')
    ),
    url(r'^', include('cloudrestapi.urls')),  
]

newCoding/ui/projects/uicloud/polls/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils import timezone

import datetime

# Create your models here.


class GlobalAppPermission(models.Model):

    class Meta:

        managed = False  # No database table creation or deletion operations \
                         # will be performed for this model. 
        #permissions = ( 
        #    ('view_polls', 'View Global polls app'),
        #    ('vendor_rigths', 'View Global polls app'),
        #)
        default_permissions = ('add', 'change', 'delete', 'view')

@python_2_unicode_compatible  # only if you need to support Python 2
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    class Meta:
        default_permissions = ('add', 'change', 'delete', 'view')
    
    def __str__(self):
        return "question_text:{0}, pub_date:{1}".format(self.question_text, self.pub_date)

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

@python_2_unicode_compatible  # only if you need to support Python 2
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return "choice_text:{0}, votes:{1}".format(self.choice_text, self.votes)

newCoding/ui/projects/uicloud/polls/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render, get_object_or_404, render_to_response
from django.urls import reverse
from django.views import generic

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required

from .models import Question, Choice
from django.db import connections

from django.utils.decorators import method_decorator
from django.views.generic.base import View
from django.views.decorators.clickjacking import xframe_options_sameorigin

# import the logging library
import logging

# Get an instance of a logger
logger = logging.getLogger(__name__)

"""
def index(request):
    
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    
    #output = '<br> '.join(["{0}:{1}".format(q.id,q.question_text) for q in latest_question_list])
    #output = "Just a test. You're at the polls index"
    
    context = {
        'latest_question_list': latest_question_list,
    }
    '''
    template = loader.get_template('polls/index.html')
    output = template.render(context,request)
    return HttpResponse(output)
    '''

    #Note that once we've done this in all these views, importing loader and HttpResponse is unnecessary.
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    #output = "You're looking at question {0}.".format(question_id)
    '''
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    '''
    question = get_object_or_404(Question, pk=question_id)

    #return HttpResponse(output) 
    return render(request, "polls/detail.html",{'question':question})

def results(request, question_id):
    question = get_object_or_404(Question,pk=question_id)

    #response = "The question:{0} <br>id:{1} <br>choice set:{2}".format(question, question_id, question.choice_set.all())
    #return HttpResponse(response)
    return render(request, 'polls/results.html', {'question': question})
"""


class IndexView(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    permission_required = ("polls.view_globalapppermission")

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

@login_required
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
    #return HttpResponse("You're voting on question %s." % question_id)

class DbView(View):
    connDict = """{
    'mysql': {
        'ENGINE': 'django.db.backends.mysql',
        'host' : '192.168.1.36',
        'database': 'mysql',
        'user' : 'root',
        'password' : 'password',
        'port' : '3306',
        'default-character-set' : 'utf8'
    },
}"""

    @method_decorator(xframe_options_sameorigin)
    def dispatch(self, *args, **kwargs):
        return super(DbView, self).dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        return render_to_response('polls/dbtest.html',
                                  {'schema': self.conn})

    def conn(self):
        conn = connections(self.connDict)
        logger.warn('LogTest {}'.format(conn))
        print(conn)
        return conn

newCoding/ui/projects/uicloud/polls/templates/polls/dbtest.html
{% extends "uiaccounts/base_site.html" %}
{% load static %}

{% block sql_explorer_content_takeover %}
<div class="schema-wrapper">
    <h4 class="text-center">Schema</h4>
    <div id="tables">
        <p class="text-center">
          <input class="search" placeholder="Search" />
        </p>
        <div class="row">
            <div class="col-xs-6 text-center">
                <a class="btn btn-link" id="collapse_all">Collapse All</a>
            </div>
            <div class="col-xs-6 text-center">
                <a class="btn btn-link" id="expand_all">Expand All</a>
            </div>
        </div>
        <ul class="list">
            {% for m in schema %}
                <li>
                    <div class="panel panel-default">
                        <div class="panel-heading schema-header">
                            <h4 class="name panel-title" style="display: inline-block">{{ m.0 }}</h4>
                        </div>
                        <div class="table-responsive schema-table">
                            <table class="table table-condensed table-hover">
                                <thead>
                                </thead>
                                <tbody>
                                    {% for c in m.1 %}
                                    <tr>
                                        <td width="50%"><code>{{ c.0 }}</code></td>
                                        <!-- This will show the type of the column as well -->
                                        <td width="50%" class="text-muted"><small>{{ c.1 }}</small></td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}
{% block sql_explorer_footer %}{% endblock %}

{% block sql_explorer_scripts %}
<script>
    $(function() {
        function SearchFocus() {
            $(".search").focus();
        }
        var options = {
            valueNames: [ 'name', 'app' ],
            handlers: { 'updated': [SearchFocus] }
        };
        var tableList = new List('tables', options);

        $('#collapse_all').click(function(){
            $('.schema-table').hide();
        });
        $('#expand_all').click(function(){
            $('.schema-table').show();
        });
        $('.schema-header').click(function(){
            $(this).parent().find('.schema-table').toggle();
        });
    });
</script>
{% endblock %}

newCoding/ui/projects/uicloud/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
<ul>
<!--{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %} -->


{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

</ul>

newCoding/ui/projects/uicloud/polls/templates/polls/index.html
{% extends "uiaccounts/base_site.html" %}
{% load i18n %}

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <!--li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li-->
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

newCoding/ui/projects/uicloud/polls/templates/polls/query.html
{% extends "explorer/base.html" %}

{% load explorer_tags %}

{% block sql_explorer_navlinks %}
    {% if can_change %}
      <li{% if not query %} class="active" {% endif %}><a href="{% url "query_create" %}">New Query</a></li>
      <li><a href="{% url "explorer_playground" %}">Playground</a></li>
    {% endif %}
    {% if query %}<li class="active"><a href="">Query Detail</a></li>{% endif %}
    <li><a href="{% url "explorer_logs" %}">Logs</a></li>
{% endblock %}

{% block sql_explorer_content %}
<div class="row">
    <div id="query_area" class="query-area col-md-12">
        <h2>{% if query %}{{ query.title }}{% if shared %}<small>&nbsp;&nbsp;shared</small>{% endif %}{% else %}New Query{% endif %}</h2>
        {% if query %}
            <div class="text-right">
                <a href="{% url "explorer_logs" %}?query_id={{ query.id }}"><h2 class="small">History</h2></a>
            </div>
        {% endif %}
        {% if message %}
            <div class="alert alert-info">{{ message }}</div>
        {% endif %}
        <div>
            {% if query %}
                <form role="form" class="form-horizontal" action="{% url "query_detail" query.id %}" method="post" id="editor">{% csrf_token %}
            {% else %}
                <form role="form" class="form-horizontal" action="{% url "query_create" %}" method="post" id="editor">{% csrf_token %}
            {% endif %}
                {% if error %}
                    <div class="alert alert-danger">{{ error|escape }}</div>
                {% endif %}
                {{ form.non_field_errors }}
                <div class="form-group">
                    {% if form.title.errors %}{% for error in form.title.errors %}
                        <div class="alert alert-danger">{{ error|escape }}</div>
                    {% endfor %}{% endif %}
                    <label for="id_title" class="col-sm-2 control-label">Title</label>
                    <div class="col-sm-10">
                        <input class="form-control" id="id_title" maxlength="255" name="title" type="text" {% if not can_change %}disabled{% endif %} value="{{ form.title.value|default_if_none:"" }}" />
                    </div>
                </div>
                <div class="form-group">
                    {% if form.description.errors %}
                        <div class="alert alert-danger">{{ form.description.errors }}</div>
                    {% endif %}
                    <label for="id_description" class="col-sm-2 control-label">Description</label>
                    <div class="col-sm-10">
                        <textarea class="form-control" cols="40" id="id_description" name="description" {% if not can_change %}disabled{% endif %} rows="2">{{ form.description.value|default_if_none:"" }}</textarea>
                    </div>
                </div>
                {% if query %}
                    <div class="form-group">
                        {% if form.created_by_user.errors %}
                            <div class="alert alert-danger">{{ form.created_by_user.errors }}</div>
                        {% endif %}
                        <label for="id_created_by_user_label" class="col-sm-2 control-label">Created By</label>
                        <div class="col-sm-10">
                            <span class="form-control" disabled id="id_created_by_user_label" maxlength="255" name="created_by_user_label">{{ form.created_by_user_email }}</span>
                            <input type="hidden" id="id_created_by_user" name="created_by_user" value="{{ form.created_by_user_email }}" />
                        </div>
                    </div>
                {% endif %}
                {% if form.sql.errors %}{% for error in form.sql.errors %}
                    <div class="alert alert-danger">{{ error|escape }}</div>
                {% endfor %}{% endif %}
                <div class="panel panel-default sql-panel">
                    <div class="panel-heading">
                      <div class="row">
                        <div class="col-md-6">
                          <span class="panel-title">SQL</span>
                        </div>
                        <div class="col-md-6 text-right">
                          {% if query %}
                            <small><a href="#" title="Open in playground" id="playground_button"><i class="glyphicon glyphicon-new-window"></i></a></small>
                          {% endif %}
                        </div>
                      </div>
                    </div>
                    <div class="panel-content">
                        <textarea class="form-control" {% if not can_change %} disabled {% endif %} cols="40" id="id_sql" name="sql" rows="20">{{ form.sql.value|default_if_none:"" }}</textarea>
                    </div>
                    {% if params %}
                      {% include 'explorer/params.html' %}
                    {% endif %}
                </div>
                <div class="form-group">
                    <div class="text-center">
                        {% if can_change %}
                            <div class="btn-group">
                              <input type="submit" value="Save & Run" class="btn btn-default" id="save_button" />
                              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="caret"></span>
                                <span class="sr-only">Toggle Dropdown</span>
                              </button>
                              <ul class="dropdown-menu">
                                {% export_buttons query %}
                                <li role="separator" class="divider"></li>
                                <li><input type="submit" value="Save Only" class="btn btn-link" id="save_only"/></li>
                              </ul>
                            </div>
                            <button type="button" class="btn btn-default" id="show_schema_button">Show Schema</button>
                            <button type="button" class="btn btn-default" id="hide_schema_button" style="display: none;">Hide Schema</button>
                            <button type="button" class="btn btn-default" id="format_button">Format</button>
                        {% else %}
                            <input type="submit" value="Refresh" class="btn btn-default" id="refresh_button" />
                            <div class="btn-group">
                              <label class="btn btn-default" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Download</label>
                              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="caret"></span>
                                <span class="sr-only">Toggle Dropdown</span>
                              </button>
                              <ul class="dropdown-menu">
                                {% export_buttons query %}
                              </ul>
                            </div>
                        {% endif %}
                    </div>
                </div>

            </form>
        </div>
    </div>
    <div id="schema" style="display: none;">
        <iframe src="" height="828px" frameBorder="0" id="schema_frame"></iframe>
    </div>
</div>
{% include 'explorer/preview_pane.html' %}
<div class="row">
  <div class="col-md-6">
    {% if query and can_change and tasks_enabled %}
      {{ form.snapshot }} Snapshot
    {% endif %}
  </div>
  <div class="col-md-6 text-right">
    {% if query.avg_duration %}
      Avg. execution: {{ query.avg_duration|floatformat:2 }}ms
    {% endif %}
  </div>
</div>
{% endblock %}

{% block sql_explorer_scripts %}
    <script>
        $(function() {
            var e = new ExplorerEditor(queryId);
        });
    </script>
{% endblock %}

newCoding/ui/projects/uicloud/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>